### ISSUE TITLE
test-x25519: strict alert check

### ISSUE THREAD

**Issue by nmav** [tomato42/tlsfuzzer#159]
The ```empty x25519 key share``` test of x25519, sends a zero length EC point, and expects a decoding error alert. However, a point of zero length, is considered an illegal (out-of-range) parameter as well, and thus the illegal parameter alert applies as well.

From rfc5246:
```
   illegal_parameter
      A field in the handshake was out of range or inconsistent with
      other fields.  This message is always fatal.

   decode_error
      A message could not be decoded because some field was out of the
      specified range or the length of the message was incorrect.  This
      message is always fatal and should never be observed in
      communication between proper implementations (except when messages
      were corrupted in the network).
```

This was uncovered at:
https://gitlab.com/gnutls/gnutls/merge_requests/514

```
test-x25519.py:stdout:Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f04c886b4d0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f04c886b510>) with last message being: <tlslite.messages.Message object at 0x7f04c87f7e90>
test-x25519.py:stdout:Error while processing
test-x25519.py:stdout:Traceback (most recent call last):
test-x25519.py:stdout:  File "scripts/test-x25519.py", line 891, in main
test-x25519.py:stdout:    runner.run()
test-x25519.py:stdout:  File "/builds/gnutls/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/tlsfuzzer/runner.py", line 178, in run
test-x25519.py:stdout:    node.process(self.state, msg)
test-x25519.py:stdout:  File "/builds/gnutls/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/tlsfuzzer/expect.py", line 571, in process
test-x25519.py:stdout:    raise AssertionError(problem_desc)
test-x25519.py:stdout:AssertionError: Expected alert description "decode_error" does not match received "illegal_parameter"
```

**Comment by tomato42** [comment]
RFC 4492:
```
        struct {
            opaque point <1..2^8-1>;
        } ECPoint;

        struct {
            ECParameters    curve_params;
            ECPoint         public;
        } ServerECDHParams;
```

zero length point is a  `decode_error, the minimal size for it is 1 byte
