### ISSUE TITLE
failure in test-fuzzed-padding.py

### ISSUE THREAD

**Issue by tomato42** [tomato42/tlsfuzzer#434]
# Bug Report

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    |  Ubuntu |
| Operating System Version |  14.04.5 LTS |
| Python version           |  3.3.6 |
| tlslite-ng version       |  tlslite-ng-0.8.0-alpha16 |
| tlsfuzzer revision       |  c993f5e05ef5b84f61|

## Problem description

Build fails in script regression testing, test-fuzzed-padding.py

## Describe how to reproduce the problem

run the test suite multiple times in travis

## Expected behaviour

no failures 

## Include errors or backtraces

```
test-fuzzed-padding.py:stdout:XOR position -1 with 0x1 ...
test-fuzzed-padding.py:stdout:Error encountered while processing node <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7fef66c4bd10> (child: <tlsfuzzer.expect.ExpectFinished object at 0x7fef66c4ba90>) with last message being: <tlslite.messages.Message object at 0x7fef62bd5d90>
test-fuzzed-padding.py:stdout:Error while processing
test-fuzzed-padding.py:stdout:Traceback (most recent call last):
test-fuzzed-padding.py:stdout:  File "scripts/test-fuzzed-padding.py", line 165, in main
test-fuzzed-padding.py:stdout:    runner.run()
test-fuzzed-padding.py:stdout:  File "/home/travis/build/tomato42/tlsfuzzer/tlsfuzzer/runner.py", line 210, in run
test-fuzzed-padding.py:stdout:    RecordHeader2)))
test-fuzzed-padding.py:stdout:AssertionError: Unexpected message from peer: Alert(fatal, bad_record_mac)
```

   <details><summary>tlslite-ng log</summary><p>

```
server:stdout:About to handshake...
server:stdout:----------------------------------------
server:stdout:Exception happened during processing of request from ('127.0.0.1', 36284)
server:stderr:Traceback (most recent call last):
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 910, in _getNextRecordFromSocket
server:stderr:    for result in self._recordLayer.recvRecord():
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/recordlayer.py", line 894, in recvRecord
server:stderr:    data = self._decryptThenMAC(header.type, data)
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/recordlayer.py", line 671, in _decryptThenMAC
server:stderr:    raise TLSBadRecordMAC()
server:stderr:tlslite.errors.TLSBadRecordMAC
server:stderr:
server:stderr:During handling of the above exception, another exception occurred:
server:stderr:
server:stderr:Traceback (most recent call last):
server:stderr:  File "/opt/python/3.3.6/lib/python3.3/socketserver.py", line 610, in process_request_thread
server:stderr:    self.finish_request(request, client_address)
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/integration/tlssocketservermixin.py", line 56, in finish_request
server:stderr:    self.RequestHandlerClass(tlsConnection, client_address, self)
server:stderr:  File "/opt/python/3.3.6/lib/python3.3/socketserver.py", line 666, in __init__
server:stderr:    self.handle()
server:stderr:  File "/opt/python/3.3.6/lib/python3.3/http/server.py", line 400, in handle
server:stderr:    self.handle_one_request()
server:stderr:  File "/opt/python/3.3.6/lib/python3.3/http/server.py", line 370, in handle_one_request
server:stderr:    self.raw_requestline = self.rfile.readline(65537)
server:stderr:  File "/opt/python/3.3.6/lib/python3.3/socket.py", line 297, in readinto
server:stderr:    return self._sock.recv_into(b)
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 485, in recv_into
server:stderr:    data = self.read(len(b))
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 235, in read
server:stderr:    for result in self.readAsync(max, min):
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 262, in readAsync
server:stderr:    allowedHsTypes):
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 681, in _getMsg
server:stderr:    for result in self._getNextRecord():
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 879, in _getNextRecord
server:stderr:    for result in self._getNextRecordFromSocket():
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 932, in _getNextRecordFromSocket
server:stderr:    "MAC failure (or padding failure)"):
server:stderr:  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tlslite/tlsrecordlayer.py", line 581, in _sendError
server:stderr:    raise TLSLocalAlert(alert, errorStr)
server:stderr:tlslite.errors.TLSLocalAlert: bad_record_mac: MAC failure (or padding failure)
```

  </p></details>

## Additional context

there may have been such failures before, but they are quite uncommon

**Comment by tomato42** [comment]
2nd failure like this, on python 3.4 this time

**Comment by NoName115** [comment]
4th failure, python 3.4

**Comment by tomato42** [comment]
5th, python 2.6

**Comment by tomato42** [comment]
6, python 3.3

**Comment by tomato42** [comment]
it looks like this is a combination of #435 and https://github.com/tomato42/tlslite-ng/pull/297

**Comment by tomato42** [comment]
seems like the above mentioned PR fixed it, closing
