### ISSUE TITLE
failure in test-tls13-finished.py

### ISSUE THREAD

**Issue by NoName115** [tomato42/tlsfuzzer#439]
# Bug Report

The test `cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 16777167` in `test-tls13-finished.py` failed in Travis build.

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    |  |
| Operating System Version |  |
| Python version           | python 3.5 |
| tlslite-ng version       | tlslite-ng>=0.8.0-alpha16 |
| tlsfuzzer revision       |  |

## Problem description
Build fails in script regression testing, test-tls13-finished.py

## Describe how to reproduce the problem
run the test mutiple times in travis

## Expected behaviour
no failures

## Include errors or backtraces

```
test-tls13-finished.py:stdout:padding - cipher TLS_AES_256_GCM_SHA384, pad_byte 0, pad_left 0, pad_right 16777167 ...
server:stdout:About to handshake...
test-tls13-finished.py:stdout:Error encountered while processing node <tlsfuzzer.expect.ExpectNewSessionTicket object at 0x7f0ec9dbbc88> (child: <tlsfuzzer.expect.ExpectNewSessionTicket object at 0x7f0ec9dbbc88>) with last message being: None
test-tls13-finished.py:stdout:Error while processing
test-tls13-finished.py:stdout:Traceback (most recent call last):
test-tls13-finished.py:stdout:  File "/home/travis/build/tomato42/tlsfuzzer/tlsfuzzer/runner.py", line 180, in run
test-tls13-finished.py:stdout:    header, parser = self.state.msg_sock.recvMessageBlocking()
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/messagesocket.py", line 101, in recvMessageBlocking
test-tls13-finished.py:stdout:    for res in self.recvMessage():
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/messagesocket.py", line 83, in recvMessage
test-tls13-finished.py:stdout:    for ret in self.recvRecord():
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/recordlayer.py", line 860, in recvRecord
test-tls13-finished.py:stdout:    for result in self._recordSocket.recv():
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/recordlayer.py", line 201, in recv
test-tls13-finished.py:stdout:    for record in self._recvHeader():
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/recordlayer.py", line 135, in _recvHeader
test-tls13-finished.py:stdout:    for result in self._sockRecvAll(1):
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/recordlayer.py", line 112, in _sockRecvAll
test-tls13-finished.py:stdout:    socketBytes = self.sock.recv(length - len(buf))
test-tls13-finished.py:stdout:  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/tlslite/bufferedsocket.py", line 54, in recv
test-tls13-finished.py:stdout:    return self.socket.recv(bufsize)
test-tls13-finished.py:stdout:socket.timeout: timed out
test-tls13-finished.py:stdout:
test-tls13-finished.py:stdout:During handling of the above exception, another exception occurred:
test-tls13-finished.py:stdout:
test-tls13-finished.py:stdout:Traceback (most recent call last):
test-tls13-finished.py:stdout:  File "scripts/test-tls13-finished.py", line 431, in main
test-tls13-finished.py:stdout:    runner.run()
test-tls13-finished.py:stdout:  File "/home/travis/build/tomato42/tlsfuzzer/tlsfuzzer/runner.py", line 196, in run
test-tls13-finished.py:stdout:    raise AssertionError("Unexpected closure from peer")
test-tls13-finished.py:stdout:AssertionError: Unexpected closure from peer
test-tls13-finished.py:stdout:
```

## Additional context
build - https://travis-ci.org/tomato42/tlsfuzzer/builds/408919292

**Comment by tomato42** [comment]
2nd failure, python 3.6

**Comment by tomato42** [comment]
3rd failure, python 3.3

**Comment by tomato42** [comment]
4th failure, python 3.4

**Comment by tomato42** [comment]
6th, python 3.2: https://travis-ci.org/tomato42/tlsfuzzer/jobs/409057346

**Comment by tomato42** [comment]
7th, python 2.7

**Comment by tomato42** [comment]
8th, python 2.6

**Comment by tomato42** [comment]
9th, python 3.5

**Comment by tomato42** [comment]
10th, python 3.6

**Comment by NoName115** [comment]
11th, python 3.3

**Comment by NoName115** [comment]
12th, python 2.7
`padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16777183` failed too

**Comment by NoName115** [comment]
13th, python 2.7
only ` 'padding - cipher TLS_AES_128_GCM_SHA256, pad_byte 0, pad_left 0, pad_right 16777183'` failed

**Comment by tomato42** [comment]
14th, python 3.5

**Comment by tomato42** [comment]
15th and 16th, python 3.2 and 3.3

**Comment by NoName115** [comment]
17th and 18th, python 2.6, python 2.7
